Upgrade old android dependencies
xuzhongpeng/qrcode_flutter pull request #17
Opened 2023-03-21 02:47 UTC by techwnn

Since there is too much old dependencies in android, upgrade related deps.
Detail change in CHANGELOG.md.

2023-03-21 02:50 UTC, techwnn commented
@xuzhongpeng , Please have a review, this pr add some technical clean and upgrade of dependencies.

2023-03-29 13:05 UTC, xuzhongpeng requested changes

2023-03-29 13:05 UTC, xuzhongpeng commented on android/build.gradle
> +        mavenCentral()
这里改成mavenCentral的原因是啥

2023-03-29 13:05 UTC, xuzhongpeng commented on example/android/app/build.gradle
> +    compileSdkVersion 33
这里建议不用写死，使用flutter.compileSdkVersion更好，根据flutter版本定义的变化，可以适配更多flutter版本

2023-03-30 02:04 UTC, techwnn commented on android/build.gradle
> +        mavenCentral()
jcenter已经废弃了，变成了只读仓库。参考官方说明： https://developer.android.google.cn/studio/build/jcenter-migration?hl=en

2023-03-30 02:35 UTC, techwnn commented on example/android/app/build.gradle
> +    compileSdkVersion 33
你说的有道理，一个插件，更应该考虑兼容多版本，我已经恢复了这个配置。

2023-03-30 12:16 UTC, xuzhongpeng approved these changes

2023-03-30 12:16 UTC, merged

2023-03-30 12:17 UTC, xuzhongpeng commented
谢谢你的贡献，已合入主分支